# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ellis Patrick - University of Sydney
email: epatrick@broadinstitute.org
description: > # this means to ignore newlines until "baseurl:"
  The website of Ellis Patrick. Harvard Medical School, Sydney University. Statistician, Computational Biologist, Bioinformatition, Alzheimer's Disease, MS, Melanoma.
# baseurl: "" # the subpath of your site, e.g. /blog
 url: "http://ellispatrick.github.io" # the base hostname & protocol for your site
twitter_username: TheEllisPatrick
github_username:  ellispatrick

# Build settings
markdown: kramdown

# Pagination
paginate: 5
paginate_path: "/news/:num/"

#gems: [jekyll-paginate]
gems:
  - jekyll-paginate
  - jekyll-seo-tag
